### ISSUE TITLE
Broken `Adoption View` link

### ISSUE THREAD

**Issue by SebastianOpriel** [eclipse-tractusx/eclipse-tractusx.github.io#689] opened 2024-02-20 13:31 UTC
Link [here](https://eclipse-tractusx.github.io/docs-kits/kits/Traceability%20Kit/Software%20Development%20View/Data%20Provider%20Development%20View%20Traceability%20Kit/#edc-policies) pointing to `Adoption View` is broken.

**Comment by mhellmeier** [comment] 2024-02-20 19:07
Thanks for the hint, but the broken links on different parts have already been addressed (duplicate of #639).

**Closed by mhellmeier** 2024-02-20 19:07 UTC
Labels: bug, duplicate
